name: Supabase Keep Alive

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          curl -X GET "https://zzzobpaunsikkxbdjyeo.supabase.co/rest/v1/Productos?select=id&limit=1" \
          -H "apikey: sb_publishable_gTZl4ULX9G7mHr7iKWjXXQ_Cwvi-52U" \
          -H "Authorization: Bearer sb_publishable_gTZl4ULX9G7mHr7iKWjXXQ_Cwvi-52U"

          curl -X GET "https://nkkyyqqqusodhwqvprik.supabase.co/rest/v1/cortes?select=id&limit=1" \
          -H "apikey: sb_publishable_0PXTRIVNAM7Kz9uDKK95IA_gCw-HHLI" \
          -H "Authorization: Bearer sb_publishable_0PXTRIVNAM7Kz9uDKK95IA_gCw-HHLI"

          curl -X GET "https://fcuyqeuakovpwspqafzx.supabase.co/rest/v1/productos?select=id&limit=1" \
          -H "apikey: sb_publishable_hEn58UnsSTQPbRbqD1uvHg_XatmgjnZ" \
          -H "Authorization: Bearer sb_publishable_hEn58UnsSTQPbRbqD1uvHg_XatmgjnZ"

          curl -X GET "https://xbmlpqkjmyldamhtzsgu.supabase.co/rest/v1/comidas?select=id&limit=1" \
          -H "apikey: sb_publishable_exApQG5qLdSFGMq9sxhnKg_T1ZnBLYs" \
          -H "Authorization: Bearer sb_publishable_exApQG5qLdSFGMq9sxhnKg_T1ZnBLYs"
